# Generated by Django 4.2.30 on 2026-07-02 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=200)),
                ('rate_type', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('parsed', models.BooleanField(default=False)),
                ('parse_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'raw_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_raw', models.CharField(max_length=200)),
                ('provider_normalized', models.CharField(db_index=True, max_length=100)),
                ('rate_type', models.CharField(db_index=True, max_length=200)),
                ('rate_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('ingestion_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(db_index=True, default='USD', max_length=10)),
                ('raw_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='rates.rawresponse')),
            ],
            options={
                'db_table': 'rates',
                'ordering': ['-effective_date', 'provider_normalized'],
                'indexes': [models.Index(fields=['provider_normalized', 'rate_type', '-effective_date'], name='idx_provider_type_date'), models.Index(fields=['ingestion_timestamp'], name='idx_ingestion_ts'), models.Index(fields=['rate_type', 'effective_date'], name='idx_rate_type_date')],
            },
        ),
    ]
